version: 3
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    groups:
      web:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/widget"
    schedule:
      interval: "weekly"
    groups:
      widget:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "k8s.io/apimachinery"
      - dependency-name: "k8s.io/client-go"
    groups:
      backend:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

 - package-ecosystem: "crates.io"
   directory: "/"
   schedule:
      interval: "weekly"
      publish: "crates.io"
